"""create_perks_venue_perks

Revision ID: 26483c8dead7
Revises: 6b6f2d0bd31b
Create Date: 2026-01-18 22:01:52.800803
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26483c8dead7'
down_revision = '6b6f2d0bd31b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perks',
    sa.Column('title_en', sa.String(length=150), nullable=False),
    sa.Column('title_ar', sa.String(length=150), nullable=False),
    sa.Column('title_fr', sa.String(length=150), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='omnia'
    )
    op.create_index(op.f('ix_perks_deleted_at'), 'perks', ['deleted_at'], unique=False, schema='omnia')
    op.create_index(op.f('ix_perks_title_ar'), 'perks', ['title_ar'], unique=False, schema='omnia')
    op.create_index(op.f('ix_perks_title_en'), 'perks', ['title_en'], unique=False, schema='omnia')
    op.create_index(op.f('ix_perks_title_fr'), 'perks', ['title_fr'], unique=False, schema='omnia')
    op.create_table('venue_perks',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('perk_id', sa.UUID(), nullable=False),
    sa.Column('perk_type', sa.Enum('EXCLUSIVE', 'BACKUP', name='venueperktype'), nullable=False),
    sa.Column('perk_mode', sa.Enum('ALWAYS_ACTIVE', 'CONDITIONAL', name='venueperkmode'), nullable=False),
    sa.Column('condition_title_en', sa.String(length=200), nullable=True),
    sa.Column('condition_title_ar', sa.String(length=200), nullable=True),
    sa.Column('condition_title_fr', sa.String(length=200), nullable=True),
    sa.Column('condition_note_en', sa.String(length=500), nullable=True),
    sa.Column('condition_note_ar', sa.String(length=500), nullable=True),
    sa.Column('condition_note_fr', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['perk_id'], ['omnia.perks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['omnia.venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='omnia'
    )
    op.create_index(op.f('ix_venue_perks_deleted_at'), 'venue_perks', ['deleted_at'], unique=False, schema='omnia')
    op.create_index(op.f('ix_venue_perks_perk_id'), 'venue_perks', ['perk_id'], unique=False, schema='omnia')
    op.create_index(op.f('ix_venue_perks_perk_mode'), 'venue_perks', ['perk_mode'], unique=False, schema='omnia')
    op.create_index(op.f('ix_venue_perks_perk_type'), 'venue_perks', ['perk_type'], unique=False, schema='omnia')
    op.create_index(op.f('ix_venue_perks_venue_id'), 'venue_perks', ['venue_id'], unique=False, schema='omnia')

    op.alter_column('resources', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='omnia')
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('resources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='omnia')
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False, schema='omnia')
    op.create_index(op.f('ix_resources_venue_id'), 'resources', ['venue_id'], unique=False, schema='omnia')
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('venues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('venues', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               schema='omnia')
    op.create_index(op.f('ix_venues_deleted_at'), 'venues', ['deleted_at'], unique=False, schema='omnia')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_deleted_at'), table_name='venues', schema='omnia')
    op.alter_column('venues', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='omnia')
    op.alter_column('venues', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('venues', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='omnia')
    op.drop_index(op.f('ix_resources_venue_id'), table_name='resources', schema='omnia')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources', schema='omnia')
    op.alter_column('resources', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='omnia')
    op.alter_column('resources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('resources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='omnia')
    op.alter_column('resources', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='omnia')

    op.drop_index(op.f('ix_venue_perks_venue_id'), table_name='venue_perks', schema='omnia')
    op.drop_index(op.f('ix_venue_perks_perk_type'), table_name='venue_perks', schema='omnia')
    op.drop_index(op.f('ix_venue_perks_perk_mode'), table_name='venue_perks', schema='omnia')
    op.drop_index(op.f('ix_venue_perks_perk_id'), table_name='venue_perks', schema='omnia')
    op.drop_index(op.f('ix_venue_perks_deleted_at'), table_name='venue_perks', schema='omnia')
    op.drop_table('venue_perks', schema='omnia')
    op.drop_index(op.f('ix_perks_title_fr'), table_name='perks', schema='omnia')
    op.drop_index(op.f('ix_perks_title_en'), table_name='perks', schema='omnia')
    op.drop_index(op.f('ix_perks_title_ar'), table_name='perks', schema='omnia')
    op.drop_index(op.f('ix_perks_deleted_at'), table_name='perks', schema='omnia')
    op.drop_table('perks', schema='omnia')
    # ### end Alembic commands ###
