"""add_featured_placement_stats_fields

Revision ID: 3e455169e798
Revises: 9c4c9022cba9
Create Date: 2026-03-07 16:04:41.363870
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e455169e798'
down_revision = '9c4c9022cba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_featured_placements', sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('venue_featured_placements', sa.Column('reach', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('venue_featured_placements', sa.Column('bookings', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue_featured_placements', 'bookings')
    op.drop_column('venue_featured_placements', 'reach')
    op.drop_column('venue_featured_placements', 'views')
    # ### end Alembic commands ###
