"""create subcategories table

Revision ID: dd5803f8a7f5
Revises: ed36484cbc41
Create Date: 2026-01-15 11:59:41.212076
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5803f8a7f5'
down_revision = 'ed36484cbc41'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_fr', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_deleted_at'), 'subcategories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subcategories_name_ar'), 'subcategories', ['name_ar'], unique=False)
    op.create_index(op.f('ix_subcategories_name_en'), 'subcategories', ['name_en'], unique=False)
    op.create_index(op.f('ix_subcategories_name_fr'), 'subcategories', ['name_fr'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('ix_categories_name_fr'), table_name='categories')
    op.create_index(op.f('ix_categories_name_fr'), 'categories', ['name_fr'], unique=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name_fr'), table_name='categories')
    op.create_index(op.f('ix_categories_name_fr'), 'categories', ['name_fr'], unique=False)
    # op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index(op.f('ix_subcategories_name_fr'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_name_en'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_name_ar'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_deleted_at'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
