"""add name_fr to category and subcategory

Revision ID: ed36484cbc41
Revises: 411a2a222243
Create Date: 2026-01-15 11:27:36.183135
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed36484cbc41'
down_revision = '411a2a222243'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        'categories',
        sa.Column('name_fr', sa.String(length=150), nullable=True)
    )

    # 2. Backfill existing rows (choose your logic)
    op.execute(
        "UPDATE categories SET name_fr = name_en WHERE name_fr IS NULL"
    )

    # 3. Make column NOT NULL
    op.alter_column(
        'categories',
        'name_fr',
        nullable=False
    )

    # 4. Create index
    op.create_index(
        op.f('ix_categories_name_fr'),
        'categories',
        ['name_fr'],
        unique=False
    )



def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name_fr'), table_name='categories')
    op.drop_column('categories', 'name_fr')
    # op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
