"""add_omnia_resource_fields

Revision ID: f9fb38292809
Revises: 26483c8dead7
Create Date: 2026-02-14 15:33:18.101018
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9fb38292809'
down_revision = '26483c8dead7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ========== RESOURCE MODULE CHANGES (OMNIA MVP) ==========
    # Add new resource fields with temporary nullable to allow data migration
    op.add_column('resources', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('resources', sa.Column('resource_name', sa.String(length=150), nullable=True))
    op.add_column('resources', sa.Column('price_per_hour', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('min_booking_hours', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('max_booking_hours', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('location_within_venue', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('amenities', sa.JSON(), nullable=True))
    op.add_column('resources', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('is_available_for_booking', sa.Boolean(), nullable=True))
    
    # Migrate existing data
    op.execute("""
        UPDATE resources 
        SET 
            resource_type = 'table',
            resource_name = COALESCE(name_en, 'Resource'),
            price_per_hour = COALESCE(base_price, 0),
            min_booking_hours = 1,
            max_booking_hours = 24,
            is_available_for_booking = true
        WHERE resource_type IS NULL
    """)
    
    # Now make required fields non-nullable
    op.alter_column('resources', 'resource_type', nullable=False)
    op.alter_column('resources', 'resource_name', nullable=False)
    op.alter_column('resources', 'price_per_hour', nullable=False)
    op.alter_column('resources', 'min_booking_hours', nullable=False)
    op.alter_column('resources', 'max_booking_hours', nullable=False)
    op.alter_column('resources', 'is_available_for_booking', nullable=False)
    
    # Make legacy fields nullable for backward compatibility
    op.alter_column('resources', 'name_en', existing_type=sa.VARCHAR(length=150), nullable=True)
    op.alter_column('resources', 'name_ar', existing_type=sa.VARCHAR(length=150), nullable=True)
    op.alter_column('resources', 'name_fr', existing_type=sa.VARCHAR(length=150), nullable=True)
    op.alter_column('resources', 'base_price', existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column('resources', 'price_unit', existing_type=sa.VARCHAR(length=50), nullable=True)
    
    # Add indexes for better query performance
    op.create_index('ix_resources_resource_type', 'resources', ['resource_type'], unique=False)
    op.create_index('ix_resources_venue_id_resource_name', 'resources', ['venue_id', 'resource_name'], unique=False)
    
    # Update timestamp columns
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    
    # Update indexes
    op.drop_index('idx_resources_venue_id', table_name='resources')
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False)
    
    # Update foreign key
    op.drop_constraint('fk_resources_venue', 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'venues', ['venue_id'], ['id'])
    
    # ========== END RESOURCE MODULE CHANGES ==========
    
    # Other table changes (bookings, categories, perks, etc.)
    op.alter_column('bookings', 'qr_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bookings', 'checked_in_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_bookings_created_by', table_name='bookings')
    op.drop_index('idx_bookings_resource_date', table_name='bookings')
    op.drop_index('idx_bookings_resource_time', table_name='bookings')
    op.drop_index('idx_bookings_venue_date', table_name='bookings')
    op.create_index('idx_booking_resource_date', 'bookings', ['resource_id', 'booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_deleted_at'), 'bookings', ['deleted_at'], unique=False)
    op.drop_constraint('fk_bookings_venue', 'bookings', type_='foreignkey')
    op.drop_constraint('fk_bookings_resource', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['checked_in_by'], ['id'])
    op.create_foreign_key(None, 'bookings', 'venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'resources', ['resource_id'], ['id'])
    op.drop_index('ux_categories_slug', table_name='categories')
    op.create_index(op.f('ix_categories_display_order'), 'categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_column('categories', 'description')
    op.alter_column('perks', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('perks', 'perk_type',
               existing_type=postgresql.ENUM('always', 'conditional', name='perk_type_enum'),
               nullable=False)
    op.alter_column('perks', 'valid_days',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('perks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('perks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('perks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_perks_venue_category', table_name='perks')
    op.create_index(op.f('ix_perks_deleted_at'), 'perks', ['deleted_at'], unique=False)
    op.drop_constraint('fk_perks_venue', 'perks', type_='foreignkey')
    op.create_foreign_key(None, 'perks', 'venues', ['venue_id'], ['id'])
    op.alter_column('pricing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_pricing_deleted_at'), 'pricing', ['deleted_at'], unique=False)
    # Skip unique constraint - data has duplicates
    # op.create_unique_constraint(None, 'pricing', ['venue_id'])
    op.drop_constraint('fk_pricing_venue', 'pricing', type_='foreignkey')
    op.create_foreign_key(None, 'pricing', 'venues', ['venue_id'], ['id'])
    op.alter_column('pricing_rules', 'active_days',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('pricing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_pricing_rules_deleted_at'), 'pricing_rules', ['deleted_at'], unique=False)
    op.add_column('resources', sa.Column('resource_type', sa.String(length=50), nullable=False))
    op.add_column('resources', sa.Column('resource_name', sa.String(length=150), nullable=False))
    op.add_column('resources', sa.Column('price_per_hour', sa.Float(), nullable=False))
    op.add_column('resources', sa.Column('min_booking_hours', sa.Integer(), nullable=False))
    op.add_column('resources', sa.Column('max_booking_hours', sa.Integer(), nullable=False))
    op.add_column('resources', sa.Column('location_within_venue', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('amenities', sa.JSON(), nullable=True))
    op.add_column('resources', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('is_available_for_booking', sa.Boolean(), nullable=False))
    op.alter_column('resources', 'name_en',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('resources', 'name_ar',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('resources', 'name_fr',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('resources', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('resources', 'price_unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_resources_venue_id', table_name='resources')
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False)
    op.drop_constraint('fk_resources_venue', 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'venues', ['venue_id'], ['id'])
    op.alter_column('venue_featured_placements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_featured_placements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_featured_placements', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_venue_featured_placements_deleted_at'), 'venue_featured_placements', ['deleted_at'], unique=False)
    op.alter_column('venue_operating_hours', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_operating_hours', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_operating_hours', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_venue_operating_hours_venue', table_name='venue_operating_hours')
    op.drop_constraint('uq_venue_day', 'venue_operating_hours', type_='unique')
    op.create_index(op.f('ix_venue_operating_hours_deleted_at'), 'venue_operating_hours', ['deleted_at'], unique=False)
    op.alter_column('venue_payment_methods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_payment_methods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_venue_payment_methods_deleted_at'), 'venue_payment_methods', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_venue_staff_pins_deleted_at'), 'venue_staff_pins', ['deleted_at'], unique=False)
    op.alter_column('venues', 'description_en',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'description_ar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'description_fr',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'address_en',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'address_ar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'address_fr',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('venues', 'image_cover',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'image_logo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'image_gallery',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'subcategory_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('venues', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('venues', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_venues_subcategory_id', table_name='venues')
    op.create_index(op.f('ix_venues_deleted_at'), 'venues', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_venues_subcategory_id'), 'venues', ['subcategory_id'], unique=False)
    op.drop_constraint('fk_venues_subcategory', 'venues', type_='foreignkey')
    op.drop_constraint('fk_venues_category', 'venues', type_='foreignkey')
    op.create_foreign_key(None, 'venues', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'venues', 'subcategories', ['subcategory_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'venues', 'users', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'venues', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ========== REVERT RESOURCE MODULE CHANGES ==========
    # Drop new indexes
    op.drop_index('ix_resources_venue_id_resource_name', table_name='resources')
    op.drop_index('ix_resources_resource_type', table_name='resources')
    
    # Restore legacy fields to non-nullable
    op.alter_column('resources', 'price_unit', existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column('resources', 'base_price', existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column('resources', 'name_fr', existing_type=sa.VARCHAR(length=150), nullable=False)
    op.alter_column('resources', 'name_ar', existing_type=sa.VARCHAR(length=150), nullable=False)
    op.alter_column('resources', 'name_en', existing_type=sa.VARCHAR(length=150), nullable=False)
    
    # Drop new columns
    op.drop_column('resources', 'is_available_for_booking')
    op.drop_column('resources', 'description')
    op.drop_column('resources', 'amenities')
    op.drop_column('resources', 'location_within_venue')
    op.drop_column('resources', 'max_booking_hours')
    op.drop_column('resources', 'min_booking_hours')
    op.drop_column('resources', 'price_per_hour')
    op.drop_column('resources', 'resource_name')
    op.drop_column('resources', 'resource_type')
    
    # Restore old indexes and foreign keys
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key('fk_resources_venue', 'resources', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources')
    op.create_index('idx_resources_venue_id', 'resources', ['venue_id'], unique=False)
    
    # Restore timestamp columns
    op.alter_column('resources', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('resources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    
    # ========== END REVERT RESOURCE MODULE CHANGES ==========
    
    # Revert other table changes
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.create_foreign_key('fk_venues_category', 'venues', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_venues_subcategory', 'venues', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_venues_subcategory_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_deleted_at'), table_name='venues')
    op.create_index('idx_venues_subcategory_id', 'venues', ['subcategory_id'], unique=False)
    op.alter_column('venues', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('venues', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('venues', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('venues', 'subcategory_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('venues', 'image_gallery',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'image_logo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'image_cover',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'address_fr',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('venues', 'address_ar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('venues', 'address_en',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('venues', 'description_fr',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('venues', 'description_ar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('venues', 'description_en',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_venue_staff_pins_deleted_at'), table_name='venue_staff_pins')
    op.drop_index(op.f('ix_venue_payment_methods_deleted_at'), table_name='venue_payment_methods')
    op.alter_column('venue_payment_methods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_payment_methods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_venue_operating_hours_deleted_at'), table_name='venue_operating_hours')
    op.create_unique_constraint('uq_venue_day', 'venue_operating_hours', ['venue_id', 'day_of_week'])
    op.create_index('idx_venue_operating_hours_venue', 'venue_operating_hours', ['venue_id'], unique=False)
    op.alter_column('venue_operating_hours', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('venue_operating_hours', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_operating_hours', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_venue_featured_placements_deleted_at'), table_name='venue_featured_placements')
    op.alter_column('venue_featured_placements', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('venue_featured_placements', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venue_featured_placements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key('fk_resources_venue', 'resources', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources')
    op.create_index('idx_resources_venue_id', 'resources', ['venue_id'], unique=False)
    op.alter_column('resources', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('resources', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'price_unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('resources', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('resources', 'name_fr',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('resources', 'name_ar',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('resources', 'name_en',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('resources', 'is_available_for_booking')
    op.drop_column('resources', 'description')
    op.drop_column('resources', 'amenities')
    op.drop_column('resources', 'location_within_venue')
    op.drop_column('resources', 'max_booking_hours')
    op.drop_column('resources', 'min_booking_hours')
    op.drop_column('resources', 'price_per_hour')
    op.drop_column('resources', 'resource_name')
    op.drop_column('resources', 'resource_type')
    op.drop_index(op.f('ix_pricing_rules_deleted_at'), table_name='pricing_rules')
    op.alter_column('pricing_rules', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pricing_rules', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing_rules', 'active_days',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.create_foreign_key('fk_pricing_venue', 'pricing', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # Skip dropping unique constraint - wasn't created
    # op.drop_constraint(None, 'pricing', type_='unique')
    op.drop_index(op.f('ix_pricing_deleted_at'), table_name='pricing')
    op.alter_column('pricing', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pricing', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'perks', type_='foreignkey')
    op.create_foreign_key('fk_perks_venue', 'perks', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_perks_deleted_at'), table_name='perks')
    op.create_index('idx_perks_venue_category', 'perks', ['venue_id', 'perk_category'], unique=False)
    op.alter_column('perks', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('perks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('perks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('perks', 'valid_days',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('perks', 'perk_type',
               existing_type=postgresql.ENUM('always', 'conditional', name='perk_type_enum'),
               nullable=True)
    op.alter_column('perks', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_display_order'), table_name='categories')
    op.create_index('ux_categories_slug', 'categories', ['slug'], unique=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('fk_bookings_resource', 'bookings', 'resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_bookings_venue', 'bookings', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_deleted_at'), table_name='bookings')
    op.drop_index('idx_booking_resource_date', table_name='bookings')
    op.create_index('idx_bookings_venue_date', 'bookings', ['venue_id', 'booking_date'], unique=False)
    op.create_index('idx_bookings_resource_time', 'bookings', ['resource_id', 'booking_date', 'start_time'], unique=False)
    op.create_index('idx_bookings_resource_date', 'bookings', ['resource_id', 'booking_date'], unique=False)
    op.create_index('idx_bookings_created_by', 'bookings', ['created_by'], unique=False)
    op.alter_column('bookings', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'checked_in_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bookings', 'qr_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
